"""NKE PROVOR CTS4 / decoder-301 Iridium-SBD telemetry front-end.

Phase 1 scope (contract: ``provor_bio_irsbd/PROVOR_CTS4_PHASE1_DESIGN_NOTE.md``
§6): raw ``.sbd`` → 140-byte framer → packet dispatch → generic cycle
attribution → raw CTD extraction.

Phase 2A scope (additive; same contract plus the Phase-2A task order): decode
of parameter packets 255/254 (:mod:`params`), technical packets 253/252/251/250
(:mod:`tech`), BGC raw extraction (:mod:`bgc`), raw→calibrated BGC equations
(:mod:`equations`), family-generic association (:mod:`assoc`), and decoder-301
label maps (:mod:`labels_301`). No calibration publication, no NetCDF emission,
no CSV writes, no WMO logic.

Byte authority: NKE ``5.8_MUT_PROVBIOII-FLBB_UTI_GB_Rev3_20130924`` §7
(first-party manual; preserved at ``provor_bio_irsbd/ref/``).

Deliberately OUT of scope: WMO naming, NetCDF emission, CSV writes, and any
change to the existing ARVOR-I (``provor_ir_sbd``) / APEX (``apex_argos``)
code. This package is standalone and imports nothing from those subpackages.
"""

from __future__ import annotations

from argo_decoder.platforms.provor_cts4_ir_sbd.assoc import (
    ProfileKey,
    group_meas,
    is_padding_ctd,
    is_padding_flbb,
    is_padding_o2,
    nearest_ctd,
)
from argo_decoder.platforms.provor_cts4_ir_sbd.bgc import (
    BGC_HEADER_LEN,
    BGC_PRES_DIVISOR,
    FLBB_COUNT_DIVISOR,
    FLBB_RECORD_STRIDE,
    FLBB_RECORDS_PER_PACKET,
    FLBB_TAIL_LEN,
    O2_PHASE_DIVISOR,
    O2_RECORD_STRIDE,
    O2_RECORDS_PER_PACKET,
    O2_TAIL_LEN,
    O2_TEMP_DIVISOR,
    O2_TEMP_OFFSET,
    SBD_EPOCH,
    FlbbPacketData,
    FlbbRecord,
    O2PacketData,
    O2Record,
    extract_flbb,
    extract_o2,
    flbb_records_for_file,
    o2_records_for_file,
    sample_datetime,
)
from argo_decoder.platforms.provor_cts4_ir_sbd.ctd import (
    CtdPacketData,
    CtdRecord,
    ctd_records_for_file,
    extract_ctd,
)
from argo_decoder.platforms.provor_cts4_ir_sbd.cycles import (
    CycleBasis,
    FileAttribution,
    GroupAttribution,
    attribute_file,
    attribute_group,
    basis_census,
    iter_group_dirs,
)
from argo_decoder.platforms.provor_cts4_ir_sbd.equations import (
    MOLAR_VOLUME_UMOL_PER_ML,
    N_FOIL_TERMS,
    DoxyResult,
    FoilCoefs,
    PhaseCoefs,
    SolubilityConsts,
    air_saturation,
    bbp700_m1,
    beta_sw,
    calphase,
    chla_ug_l,
    cstar,
    doxy_chain,
    doxy_umol_kg,
    foil_delta_p,
    molar_doxy,
    p_h2o,
    phase_pcorr,
    pressure_correction,
    salinity_correction,
    tphase,
    ts_ratio,
    vapour_pressure,
)
from argo_decoder.platforms.provor_cts4_ir_sbd.framer import (
    FramedFile,
    FramingError,
    frame_bytes,
    frame_file,
)
from argo_decoder.platforms.provor_cts4_ir_sbd.labels_301 import (
    DERIVED_ONLY_CONFIG_LABELS,
    DERIVED_ONLY_TECH_LABELS,
    PM_CONFIG_LABEL,
    PT_CONFIG_LABEL,
    PV_CONFIG_LABEL,
    SENSOR_250_NAMES,
    SHORT_SENSOR_251_NAMES,
    TECH250_CTD_FREE_LABEL,
    TECH250_FLBB_FREE_LABEL,
    TECH250_LABEL,
    TECH253_LABEL,
    CoverageReport,
    coverage,
)
from argo_decoder.platforms.provor_cts4_ir_sbd.packets import (
    DispatchedFile,
    DispatchError,
    MeasPacket,
    MeasSubtype,
    OpaquePacket,
    PacketType,
    ParamPacket,
    UnknownMeasSubtypeError,
    UnknownPacketTypeError,
    dispatch_framed,
    dispatch_row,
)
from argo_decoder.platforms.provor_cts4_ir_sbd.params import (
    MISSION_SPARE_LEN,
    MISSION_SPARE_OFFSET,
    N_PM_PROFILES,
    N_PT_WORDS,
    N_PV_DURATIONS,
    PACKET_LEN,
    PARAMS_OFFSET,
    PM_PROFILE_STRIDE,
    PM_PROFILES_OFFSET,
    PT_NAMES,
    PT_STRIDE,
    PT_UNITS,
    PV_DURATION_STRIDE,
    PV_DURATIONS_OFFSET,
    TECH_SPARE_LEN,
    TECH_SPARE_OFFSET,
    CycleDuration,
    MissionParams,
    MissionProfile,
    TechParams,
    decode_254,
    decode_255,
)
from argo_decoder.platforms.provor_cts4_ir_sbd.tech import (
    FILLER_SENSOR_ID,
    FREE_LEN,
    FREE_OFFSET_IN_HALF,
    HALF_LEN,
    N_HALVES,
    PARAMS_CHANGE_STRIDE,
    PARAMS_CHANGES_OFFSET,
    PARAMS_N_CHANGES,
    PARAMS_SPARE_LEN,
    PRESSURE_N_SAMPLES,
    PRESSURE_SAMPLES_OFFSET,
    PRESSURE_SPARE_LEN,
    PRESSURE_STRIDE,
    SENSOR_NAMES,
    VECTOR_SPARE_LEN,
    VECTOR_SPARE_OFFSET,
    CtdFree,
    FlbbFree,
    FloatTime,
    OptodeFree,
    PressurePacket,
    PressureSample,
    SensorHalf,
    SensorParamChange,
    SensorParams,
    SensorTechPacket,
    UnknownSensorTypeError,
    VectorTech,
    battery_dropout_v,
    battery_voltage_v,
    decode_250,
    decode_251,
    decode_252,
    decode_253,
    gps_decimal,
    hhmm_from_minutes,
    vacuum_mbar_x5,
)

__all__ = [
    "BGC_HEADER_LEN",
    "BGC_PRES_DIVISOR",
    "DERIVED_ONLY_CONFIG_LABELS",
    "DERIVED_ONLY_TECH_LABELS",
    "FILLER_SENSOR_ID",
    "FLBB_COUNT_DIVISOR",
    "FLBB_RECORDS_PER_PACKET",
    "FLBB_RECORD_STRIDE",
    "FLBB_TAIL_LEN",
    "FREE_LEN",
    "FREE_OFFSET_IN_HALF",
    "HALF_LEN",
    "MISSION_SPARE_LEN",
    "MISSION_SPARE_OFFSET",
    "MOLAR_VOLUME_UMOL_PER_ML",
    "N_FOIL_TERMS",
    "N_HALVES",
    "N_PM_PROFILES",
    "N_PT_WORDS",
    "N_PV_DURATIONS",
    "O2_PHASE_DIVISOR",
    "O2_RECORDS_PER_PACKET",
    "O2_RECORD_STRIDE",
    "O2_TAIL_LEN",
    "O2_TEMP_DIVISOR",
    "O2_TEMP_OFFSET",
    "PACKET_LEN",
    "PARAMS_CHANGES_OFFSET",
    "PARAMS_CHANGE_STRIDE",
    "PARAMS_N_CHANGES",
    "PARAMS_OFFSET",
    "PARAMS_SPARE_LEN",
    "PM_CONFIG_LABEL",
    "PM_PROFILES_OFFSET",
    "PM_PROFILE_STRIDE",
    "PRESSURE_N_SAMPLES",
    "PRESSURE_SAMPLES_OFFSET",
    "PRESSURE_SPARE_LEN",
    "PRESSURE_STRIDE",
    "PT_CONFIG_LABEL",
    "PT_NAMES",
    "PT_STRIDE",
    "PT_UNITS",
    "PV_CONFIG_LABEL",
    "PV_DURATIONS_OFFSET",
    "PV_DURATION_STRIDE",
    "SBD_EPOCH",
    "SENSOR_250_NAMES",
    "SENSOR_NAMES",
    "SHORT_SENSOR_251_NAMES",
    "TECH250_CTD_FREE_LABEL",
    "TECH250_FLBB_FREE_LABEL",
    "TECH250_LABEL",
    "TECH253_LABEL",
    "TECH_SPARE_LEN",
    "TECH_SPARE_OFFSET",
    "VECTOR_SPARE_LEN",
    "VECTOR_SPARE_OFFSET",
    "X_OFFSET_IN_HALF",
    "CoverageReport",
    "CtdFree",
    "CtdPacketData",
    "CtdRecord",
    "CycleBasis",
    "CycleDuration",
    "DispatchError",
    "DispatchedFile",
    "DoxyResult",
    "FileAttribution",
    "FlbbFree",
    "FlbbPacketData",
    "FlbbRecord",
    "FloatTime",
    "FoilCoefs",
    "FramedFile",
    "FramingError",
    "GroupAttribution",
    "MeasPacket",
    "MeasSubtype",
    "MissionParams",
    "MissionProfile",
    "OpaquePacket",
    "OptodeFree",
    "PacketType",
    "ParamPacket",
    "PhaseCoefs",
    "PressurePacket",
    "PressureSample",
    "ProfileKey",
    "SensorHalf",
    "SensorParamChange",
    "SensorParams",
    "SensorTechPacket",
    "SolubilityConsts",
    "TechParams",
    "UnknownMeasSubtypeError",
    "UnknownPacketTypeError",
    "UnknownSensorTypeError",
    "VectorTech",
    "air_saturation",
    "attribute_file",
    "attribute_group",
    "basis_census",
    "battery_dropout_v",
    "battery_voltage_v",
    "bbp700_m1",
    "beta_sw",
    "calphase",
    "chla_ug_l",
    "coverage",
    "cstar",
    "ctd_records_for_file",
    "decode_250",
    "decode_251",
    "decode_252",
    "decode_253",
    "decode_254",
    "decode_255",
    "dispatch_framed",
    "dispatch_row",
    "doxy_chain",
    "doxy_umol_kg",
    "extract_ctd",
    "extract_flbb",
    "extract_o2",
    "flbb_records_for_file",
    "foil_delta_p",
    "frame_bytes",
    "frame_file",
    "gps_decimal",
    "group_meas",
    "hhmm_from_minutes",
    "is_padding_ctd",
    "is_padding_flbb",
    "is_padding_o2",
    "molar_doxy",
    "nearest_ctd",
    "o2_records_for_file",
    "p_h2o",
    "phase_pcorr",
    "pressure_correction",
    "salinity_correction",
    "sample_datetime",
    "tphase",
    "ts_ratio",
    "vacuum_mbar_x5",
    "vapour_pressure",
]
