$ Mission configuration for Apf9i(9567) FwRev 012811:
$ AscentTimeOut(540) [min]
$ AtDialCmd(AT+CBST=71,0,1;DT0088160000573) [primary]
$ AltDialCmd(AT+CBST=7,0,1;DT0013016366303) [alternate]
$ BuoyancyNudge(10) [count]
$ BuoyancyNudgeInitial(22) [count]
$ ConnectTimeOut(60) [sec]
$ CpActivationP(500) [dbar]
$ DeepProfileDescentTime(300) [min]
$ DeepProfilePistonPos(14) [count]
$ DeepProfilePressure(2000) [dbar]
$ CompensatorHyperRetraction(254) [count]
$ DownTime(13740) [min]
$ FloatId(9567)
$ FullExtension(227) [count]
$ FullRetraction(9) [count]
$ MaxAirBladder(124) [count]
$ MaxLogKb(40) [KByte]
$ MissionPrelude(360) [min]
$ OkVacuum(96) [count]
$ PActivationPistonPosition(16) [count]
$ ParkDescentTime(300) [min]
$ ParkPistonPos(53) [count]
$ ParkPressure(1000) [dbar]
$ PnPCycleLen(1)
$ TelemetryRetry(15) [min]
$ TimeOfDay(DISABLED) [min]
$ UpTime(660) [min]
$ Verbosity(2)
$ DebugBits(0x0002)
$
ParkPts:    Jan 25 2016 03:02:29  1453690949   18036  920.56  7.1239 34.9529
ParkPts:    Jan 25 2016 04:02:26  1453694546   21633  932.10  7.1273 34.9528
ParkPts:    Jan 25 2016 05:02:26  1453698146   25233  940.51  7.1034 34.9519
ParkPts:  