# GPS fix obtained in 58 seconds.
#         lon     lat mm/dd/yyyy hhmmss nsat
Fix:   63.936  16.057 10/04/2016 163420   10
Apf9iFwRev=061016
ActiveBallastAdjustments=0
AirBladderPressure=127
AirPumpAmps=72
AirPumpVolts=198
BuoyancyPumpOnTime=1192
BuoyancyPumpAmps=0
BuoyancyPumpVolts=0
CurrentPistonPosition=226
DeepProfilePistonPosition=16
GpsFixTime=58
FlashErrorsCorrectable=0
FlashErrorsUncorrectable=0
FloatId=7827
ParkDescentPCnt=0
ParkPistonPosition=66
ParkObs={ 0.0dbar, 0.000C, 0.0000PSU / 0.000 0.000C 0.000 / 0, 0, 0}
ProfileId=000
ObsIndex=0
QuiescentAmps=0
QuiescentVolts=0
RtcSkew=4
Sbe41cpAmps=0
Sbe41cpVolts=0
Sbe41cpStatus=0x00000000
status=0x00000000
SurfaceObs={ 0.1dbar, nan, nan / 27.040 29.220C 8.969 / 146, 235, 534}
SurfacePistonPosition=0
SurfacePressure=0.00
Vacuum=88

<EOT>

<EOT>
