"""Structural parity test: run Python against demo data using the CSV
metadata backend and compare against the bootstrapped golden tree.

The golden tree is generated by ``scripts/bootstrap_golden.py``. When we
capture MATLAB outputs for the demo WMOs, the same test can be re-pointed
at the MATLAB golden to produce a true parity gate.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from argo_decoder.config import DecoderConfig
from argo_decoder.pipeline.comparator import compare_outputs
from argo_decoder.pipeline.runner import run_pipeline

REPO_ROOT = Path(__file__).resolve().parents[2]
GOLDEN = REPO_ROOT / "tests" / "golden" / "expected"


@pytest.mark.skipif(not GOLDEN.exists(), reason="golden tree not yet bootstrapped")
def test_csv_backend_matches_golden_structurally(demo_input: Path, tmp_path: Path):
    out = tmp_path / "out"
    for name in ("xml", "nc", "log", "csv", "iridium", "tmp"):
        (out / name).mkdir(parents=True)

    cfg = DecoderConfig()
    cfg.metadata.backend = "csv"  # type: ignore[assignment]
    cfg.metadata.registry_path = REPO_ROOT / "config" / "registry.csv"
    cfg.paths.rsync_data_dir = demo_input / "archive" / "cycle"
    cfg.paths.rsync_log_dir = demo_input / "rsync_list"
    cfg.paths.xml_dir = out / "xml"
    cfg.paths.nc_dir = out / "nc"
    cfg.paths.log_dir = out / "log"
    cfg.paths.csv_dir = out / "csv"
    cfg.paths.iridium_decoded_dir = out / "iridium"
    cfg.paths.temporary_dir = out / "tmp"

    result = run_pipeline(
        config=cfg,
        wmo=6902892,
        xml_filename="co041404_golden_6902892.xml",
        use_null_decoder=True,
    )
    assert result.status == "ok"
    assert result.n_cycles == 2215

    # Compare to golden. Ignore volatile XML fields (decoder_version,
    # duration_seconds, start_date, message) which include timestamps.
    report = compare_outputs(GOLDEN, out, wmo=6902892)
    errors = [m for m in report.mismatches if m.severity == "error"]
    assert not errors, "Structural mismatches:\n" + "\n".join(
        f"  {m.scope} {m.file} {m.variable or ''}: {m.message}" for m in errors
    )
